services:
  # バックエンドサービス
  backend:
    build: ./backend
    # コンテナ名を指定
    container_name: sample-backend
    env_file:
      - ./backend/.env

  # フロントエンドサービス
  frontend:
    build: ./frontend
    container_name: sample-nextjs-frontend
    ports:
      - "3000:3000" # Next.jsは3000番ポートで動作
    depends_on:
      - backend
    restart: unless-stopped