# version: '3.8'

services:
  # バックエンドサービス
  backend:
    build: ./backend
    # コンテナ名を指定
    container_name: sample-backend
    ports:
      - "3000:3000"
    environment:
      # データベース接続URLを環境変数として設定
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"
    # dbサービスが起動してからbackendを起動する
    depends_on:
      db:
        condition: service_healthy

  # フロントエンドサービス
  frontend:
    build: ./frontend
    container_name: sample-frontend
    ports:
      # ホストPCの8080ポートをコンテナの80ポートにマッピング
      - "8080:80"
    # backendサービスが起動してからfrontendを起動する
    depends_on:
      - backend

  # PostgreSQLサービス
  db:
    image: postgres:14
    container_name: sample-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      # デバッグ用にホストPCの5432ポートをコンテナの5432ポートにマッピング
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: